main_apps/blog/urls.py
from django.urls import path
from blog.views import show_blogs

app_name = 'blog'

urlpatterns = [
    path('blog/', show_blogs),
]

main_apps/main_apps/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('portfolio.urls', namespace='portfolio')),
    path('projects', include('projects.urls', namespace='projects')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_apps/portfolio/urls.py
from django.urls import path
from portfolio.views import show_portfolio

app_name = 'portfolio'

urlpatterns = [
    path('', show_portfolio, name='index'),
]

main_apps/projects/urls.py
from django.urls import path
from projects.views import age_calculator, calculator_currency, show_weather

app_name = 'projects'

urlpatterns = [
    path('age_calculator', age_calculator, name='age_calculator'),
    path('calculator_currency', calculator_currency, name='calculator_currency'),
    path('show_weather', show_weather, name='show_weather'),
]

main_apps/blog/models.py
from django.db import models

# Create your models here.

main_apps/portfolio/models.py
from django.db import models

# Create your models here.

class Portfolio(models.Model):
    title = models.CharField(max_length=100)
    descriptions = models.CharField(max_length=300)
    text = models.TextField()
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    git_hub_url = models.URLField(blank=True, null=True)

main_apps/projects/models.py
from django.db import models

# Create your models here.

main_apps/users/models.py
from django.db import models

# Create your models here.

main_apps/projects/forms.py
from django import forms


class CalculateAge(forms.Form):
    name = forms.CharField(max_length=50)
    date_birth = forms.IntegerField()


class CalculateCurrency(forms.Form):
    OPTIONS = [
        ("DOL", "Dollar"),
        ("EUR", "EUR"),
        ]

    currency = forms.ChoiceField(
            choices=OPTIONS,
            label='Office',
        )
    amount = forms.IntegerField()


class CalculateWeather(forms.Form):
    city = forms.CharField(max_length=50)

main_apps/blog/views.py
from django.shortcuts import render

# Create your views here.

def show_blogs(request):
    return render(request, 'blog/blog.html')

main_apps/portfolio/views.py
from django.shortcuts import render
from portfolio.models import Portfolio

# Create your views here.


def show_portfolio(request):
    projects = Portfolio.objects.all()
    context = {'projects': projects}
    return render(request, 'portfolio/portfolio.html', context)

main_apps/projects/views.py
from django.shortcuts import render
from django.http import HttpResponse
from projects.forms import CalculateAge, CalculateCurrency, CalculateWeather
from projects.calculators import calculate_age, calculate_currency_DOLLAR_RUB
from projects.weather_calculate import get_weather_at_city

# Create your views here.


def age_calculator(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        age = request.POST.get("date_birth")
        age = calculate_age(age)
        context = {
            'show_form': False,
            'hi': 'Hello',
            'name': name,
            'date_birth': age
        }
        return render(request, 'projects/age_calculator.html', context)
    else:
        form = CalculateAge()
        context = {
            'show_form': True,
            'hi': 'Hello',
            'form': form
        }
        return render(request, 'projects/age_calculator.html', context)


def calculator_currency(request):
    if request.method == 'POST':
        currency = request.POST.get("currency")
        amount = request.POST.get("amount")
        if currency == 'DOL':
            currency = calculate_currency_DOLLAR_RUB(amount)
            context = {
                'show_form': False,
                'amount': amount,
                'currency': currency,
            }
            return render(request, 'projects/current_dollar.html', context)
    else:
        form = CalculateCurrency()
        context = {
            'show_form': True,
            'form': form
        }
        return render(request, 'projects/current_dollar.html', context)


def show_weather(request):
    form = CalculateWeather
    context = {
        'form': form
    }
    if request.method == 'POST':
        city = request.POST.get("city")
        weather = get_weather_at_city(city)
        context["weather"] = weather
        return render(request, 'projects/weather.html', context)
    else:
        return render(request, 'projects/weather.html', context)

main_apps/users/views.py
from django.shortcuts import render

# Create your views here.

main_apps/blog/templates/blog/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>First Page Index</h1>
    <p>Hello world!</p>
</body>
</html>

main_apps/portfolio/templates/portfolio/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

     <a href="{% url 'portfolio:index' %}">Main. Portfolio</a><br>
     <a href="{% url 'projects:age_calculator' %}">age_calculator</a><br>
     <a href="{% url 'projects:calculator_currency' %}">calculator_currency</a><br>
     <a href="{% url 'projects:show_weather' %}">calculator_weather</a><br>


    {% block content %}{% endblock %}

    {% block footer %}{% endblock %}


</body>
</html>

main_apps/portfolio/templates/portfolio/portfolio.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block title %} Main. Portfolio {% endblock %}


    {% block content %}
        <div> Main screen
        <h1> My Portfolio</h1>
    </div>
    <div>
        <br><br>
        projects
            <h2>Мои проекты</h2>

        {% for project in projects %}
        <hr>
            <h3>{{ project.title }}</h3>
            <p>{{ project.descriptions }}</p>
            <p>{{ project.text }}</p>
            <p><img src="{{ project.image.url }}" alt="{{ project.title }}"></p>
            <p>{{ project.git_hub_url }}</p>
        <br>

        {% endfor %}

    </div>
    {% endblock %}

    {% block footer %}{% endblock %}






</body>
</html>

main_apps/projects/templates/projects/age_calculator.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block title %} Main. Age calculator {% endblock %}


    {% block content %}
    Main screen
    <h1> My Portfolio</h1>

        <br><br>
        projects
            <h2>Мои проекты</h2>
    {% if show_form %}
        <form method="POST">
            {% csrf_token %}

            {{ form.as_p }}

        <input type="submit">
        </form>
    {% else %}
    <h4>{{ name }} ваш возраст {{ date_birth }}</h4>
    {% endif %}

    {% endblock %}

    {% block footer %}{% endblock %}






</body>
</html>

main_apps/projects/templates/projects/current_dollar.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block title %} Main. Current Dollar {% endblock %}


    {% block content %}
    Main screen
    <h1> Current Dollar </h1>

        <br><br>

    {% if show_form %}
        <form method="POST">
            {% csrf_token %}

            {{ form }}

        <input type="submit">
        </form>
    {% else %}
    <h4>{{ amount }} рублей в долларах по курсу на данный момент это :<br>{{ currency }} долларов</h4>
    {% endif %}

    {% endblock %}

    {% block footer %}{% endblock %}






</body>
</html>

main_apps/projects/templates/projects/projects.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block title %} Main. Portfolio {% endblock %}


    {% block content %}
    Main screen
    <h1> My Portfolio</h1>

        <br><br>
        projects
            <h2>Мои проекты</h2>
    {% if show_form %}
        <form method="POST">
            {% csrf_token %}

            {{ form }}

        <input type="submit">
        </form>
    {% else %}
    <h4>{{ name }} ваш возраст {{ age }}</h4>
    {% endif %}

    {% endblock %}

    {% block footer %}{% endblock %}






</body>
</html>

main_apps/projects/templates/projects/weather.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block title %} Weather {% endblock %}

{% block content %}
    Main screen
    <h1> Weather</h1>

        <br><br>
        projects
            <h2>Weather in the City</h2>

        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
        <input type="submit">
        </form>

    <h4>{{ weather }}</h4>

{% endblock %}

{% block footer %}{% endblock %}






</body>
</html>